title: Cracking-LeetCode
description:
  I post my notes on solving LeetCode algorithm problems on this site.
  This page is hosted on GitHub Pages, and the theme is created by David Freeman.
permalink: ':title/'
baseurl: "/Cracking-LeetCode" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jie Cheng # add your name
author-img: jie-cheng.jpg # add your photo
about-author: I am a C++ programmer focusing on scientific computing. I solve algorithm problems on LeetCode for fun. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: Jie-Cheng # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
